[package]
name = "unicorn"
version = "0.9.0"
authors = ["Sébastien Duquette <ekse.0x@gmail.com>", "Lucca Fraser <lucca.fraser@gmail.com>"]
documentation = "https://docs.rs/unicorn/"
edition = "2018"
include = [
    "/.gitmodules",
    "/COPYING",
    "/Cargo.toml",
    "/README.md",
    "/src/*",
]
license = "GPL-2.0"
readme = "README.md"
repository = "https://github.com/oblivia-simplex/unicorn-rs"
description = "Rust bindings for the unicorn emulator"

[dependencies]
bitflags = "1.0"
enum-utils = "0.1"
libc = "0.2"
libunicorn-sys = { path = "libunicorn-sys", version = "0.9.0" }
log = "0.4"
pretty_env_logger = "0.4"
paste = "0.1"
serde = { version = "1", features = ["derive"]}
toml = "0.5"
